"""Plan 251: @generated banner provenance."""

from __future__ import annotations

from pathlib import Path

from agentscaffold.rendering import (
    MANAGED_BLOCK_BEGIN,
    generated_banner,
    prepend_generated_banner,
    stamp_guidance,
    write_managed_block,
)


def test_banner_is_relative_and_names_the_generator() -> None:
    text = generated_banner(
        generator="scaffold agents generate-all",
        source="docs/ai/routing.md",
        digest="abc123",
    )
    assert text.startswith("<!-- @generated by scaffold agents generate-all")
    assert "source=docs/ai/routing.md" in text
    assert "sha256=abc123" in text
    assert "/Users/" not in text


def test_absolute_source_is_reduced_to_the_basename() -> None:
    text = generated_banner(
        generator="scaffold agents generate-all",
        source="/Users/someone/repo/docs/ai/routing.md",
        digest="abc123",
    )
    assert "source=routing.md" in text
    assert "/Users/someone" not in text


def test_hash_changes_when_source_digest_changes() -> None:
    a = generated_banner(generator="g", source="a.md", digest="1")
    b = generated_banner(generator="g", source="a.md", digest="2")
    assert a != b


def test_banner_sits_after_mdc_frontmatter() -> None:
    body = "---\nalwaysApply: true\n---\nUse this file.\n"
    out = prepend_generated_banner(
        body,
        generator="scaffold agents generate-all",
        source=".cursor/rules/agentscaffold.mdc",
        digest="ff",
    )
    assert out.startswith("---\n")
    assert "<!-- @generated by scaffold agents generate-all" in out
    assert out.index("---") < out.index("@generated")


def test_stamp_guidance_includes_banner_and_trailing_hash() -> None:
    out = stamp_guidance("# body\n", "a" * 64, "docs/ai/routing.md")
    assert "@generated by scaffold agents generate-all" in out
    assert "agentscaffold-guidance-sha256" in out
    assert "source=docs/ai/routing.md" in out or "source: docs/ai/routing.md" in out


def test_human_text_outside_managed_markers_survives(tmp_path: Path) -> None:
    path = tmp_path / "AGENTS.md"
    path.write_text("# Human header\n\nKeep me.\n")
    write_managed_block(path, "generated body v1")
    write_managed_block(path, "generated body v2")
    text = path.read_text()
    assert text.startswith("# Human header")
    assert "Keep me." in text
    assert "generated body v2" in text
    assert "generated body v1" not in text
    assert MANAGED_BLOCK_BEGIN in text
