"""Plan 251 C3: compact vs full guidance stamp."""

from __future__ import annotations

from pathlib import Path

from agentscaffold.mcp.scope_stamp import compact_guidance_stamp, full_guidance_stamp

_DIARY = {"stats", "hot_files", "recent_plans", "recent_studies", "active_adrs"}


def _project_with_guidance(tmp_path: Path) -> Path:
    root = tmp_path / "proj"
    rules = root / ".cursor" / "rules"
    rules.mkdir(parents=True)
    (rules / "agentscaffold.mdc").write_text(
        "---\nalwaysApply: true\n---\n<!-- @generated by scaffold agents generate-all -->\n"
    )
    (root / "AGENTS.md").write_text("# Agent Operating Rules\n")
    return root


def test_compact_stamp_is_workspace_relative(tmp_path: Path) -> None:
    root = _project_with_guidance(tmp_path)
    stamp = compact_guidance_stamp(root)
    assert stamp["guidance_rule_path"] == ".cursor/rules/agentscaffold.mdc"
    assert stamp["guidance_is_generated"] is True
    assert not str(stamp["guidance_rule_path"]).startswith("/")
    assert _DIARY.isdisjoint(stamp)


def test_full_stamp_lists_copies_without_diary_keys(tmp_path: Path) -> None:
    root = _project_with_guidance(tmp_path)
    (root / "CLAUDE.md").write_text("x")
    stamp = full_guidance_stamp(root)
    assert stamp["guidance_rule_path"] == ".cursor/rules/agentscaffold.mdc"
    assert ".cursor/rules/agentscaffold.mdc" in stamp["guidance_copies"]
    assert "AGENTS.md" in stamp["guidance_copies"]
    assert "CLAUDE.md" in stamp["guidance_copies"]
    assert _DIARY.isdisjoint(stamp)


def test_missing_guidance_file_still_emits_stamp_keys(tmp_path: Path) -> None:
    root = tmp_path / "empty"
    root.mkdir()
    stamp = compact_guidance_stamp(root)
    assert stamp["guidance_rule_path"] is None
    assert stamp["guidance_is_generated"] is False
    assert _DIARY.isdisjoint(stamp)


def test_dispatch_carries_compact_stamp(two_project_workspace) -> None:
    from agentscaffold.mcp.server import _dispatch_tool

    ws = two_project_workspace
    payload = _dispatch_tool(
        "scaffold_stats",
        {"working_path": str(ws.source_file(ws.alpha_name))},
    )
    meta = payload["meta"]
    assert "guidance_rule_path" in meta
    assert "guidance_is_generated" in meta
    path = meta["guidance_rule_path"]
    if path:
        assert not path.startswith("/")
        assert "/Users/" not in path
    assert _DIARY.isdisjoint(payload.get("guidance") or {})


def test_orient_summary_does_not_restore_diary_keys(two_project_workspace) -> None:
    from agentscaffold.mcp.server import _dispatch_tool

    ws = two_project_workspace
    payload = _dispatch_tool(
        "scaffold_orient",
        {"working_path": str(ws.source_file(ws.alpha_name)), "detail": "summary"},
    )
    assert payload.get("detail") == "summary"
    for key in _DIARY:
        assert key not in payload
    guidance = payload.get("guidance") or {}
    assert "guidance_rule_path" in guidance
    assert _DIARY.isdisjoint(guidance)
