"""Windsurf hook generator — Step B.4.

Windsurf Cascade uses ``.windsurfrules`` (instructional enforcement, no
native hook/script mechanism yet).  This generator appends enforcement rule
instructions to the ``.windsurfrules`` file generated by ``scaffold agents
windsurf``.
"""

from __future__ import annotations

from pathlib import Path

from agentscaffold.hooks.config import EnforcementConfig, HookRuleConfig


def _rule_to_instruction(rule: HookRuleConfig) -> str:
    """Convert a hook rule to a plain-text instruction for .windsurfrules."""
    parts: list[str] = []
    event_label = rule.event.value
    if rule.description:
        parts.append(f"- **{event_label}**: {rule.description}")
    elif rule.command:
        parts.append(f"- **{event_label}**: run `{rule.command}`")
    else:
        parts.append(f"- **{event_label}** (enabled)")
    return "\n".join(parts)


def generate_windsurf_enforcement_section(config: EnforcementConfig) -> str:
    """Generate the enforcement instructions block for ``.windsurfrules``.

    Returns:
        A markdown block that can be appended to ``.windsurfrules``.
    """
    rules = config.rules_for_platform("windsurf")
    lines: list[str] = ["", "## Enforcement Rules", ""]

    # Built-ins
    if config.freshness_trigger:
        lines.append(
            "- **PostToolUse** (Edit/Write): run `scaffold index --incremental` "
            "to keep the knowledge graph fresh."
        )
    if config.auto_orient:
        lines.append("- **SessionStart**: run `scaffold orient` to load current context.")

    for rule in rules:
        lines.append(_rule_to_instruction(rule))

    return "\n".join(lines) + "\n"


def write_windsurf_hooks(
    config: EnforcementConfig,
    output_dir: Path,
    *,
    dry_run: bool = False,
) -> Path:
    """Append enforcement section to ``.windsurfrules``.

    Args:
        config: Enforcement configuration.
        output_dir: Project root directory.
        dry_run: If True, return the target path without writing anything.

    Returns:
        Path to ``.windsurfrules``.
    """
    rules_path = output_dir / ".windsurfrules"

    if dry_run:
        return rules_path

    if not config.platform_enabled("windsurf"):
        return rules_path

    section = generate_windsurf_enforcement_section(config)

    if rules_path.is_file():
        existing = rules_path.read_text()
        if "## Enforcement Rules" not in existing:
            rules_path.write_text(existing.rstrip() + "\n" + section)
    else:
        rules_path.write_text(section)

    return rules_path
