"""Stable workspace identifiers (Plan 249).

A workspace id keys the workspace's entry in the user-level registry and, from
Phase B, the directory holding its relocated graph state.

The id is random rather than derived from the workspace path. That is deliberate
twice over: a path-derived id would orphan a workspace's state the moment the
root is moved or renamed, and it would leak the filesystem layout of a user's
projects into a directory listing of the shared state location.
"""

from __future__ import annotations

import re
import secrets

#: Prefix marking a value as a workspace id, so ids stay recognisable in paths,
#: manifests, and error messages.
WORKSPACE_ID_PREFIX = "ws-"

#: Number of random bytes behind a generated id. Six bytes is 48 bits, which is
#: far more than a single user's workspace count needs and keeps the id short
#: enough to read in a path.
_ID_ENTROPY_BYTES = 6

#: Accepts any lowercase-hex body of a plausible length, so ids generated by a
#: different release (or the shorter form in the interface contract's example)
#: still validate.
_WORKSPACE_ID_RE = re.compile(r"^ws-[0-9a-f]{6,32}$")


def generate_workspace_id() -> str:
    """Return a fresh, opaque workspace id such as ``ws-7f3a9c1b2d4e``."""
    return f"{WORKSPACE_ID_PREFIX}{secrets.token_hex(_ID_ENTROPY_BYTES)}"


def is_valid_workspace_id(value: str) -> bool:
    """Return True when *value* is a well-formed workspace id.

    Validation is strict so a hand-edited registry fails loudly rather than
    producing a state directory named after a typo.
    """
    if not value:
        return False
    return bool(_WORKSPACE_ID_RE.match(value))
